### ISSUE TITLE
สอบถามเรื่อง atomymaxsite

### ISSUE THREAD

**Issue by pawarit123** [robocon/easy1-template#1]
พอดีลง atomymaxsite 2.5 ผ่าน appserv  เสร็จแล้ว ก็ปรับแต่งเวบมาเรื่อย ๆ ไม่มีปัญหาอะไร แต่พอจะต้องการเปลี่ยนหน้า admin  เกิดปัญหา หน้าเว็บแจ้ง ว่า  "ท่านพยายามจะ hack ระบบของเราครับ ระบบได้ส่งของมูล IP ของท่านไปให้ผู้มีส่วนเกี่ยวข้องแล้ว "  เป็นแบบนี้อะครับ ทั้งที่ผมเป็น admin  ก็ไม่สามารถเข้าได้  ลองเอาไปลง ในเครื่องอื่น ก็ไม่ได้ เปลี่ยน ไอพี เคื่องตัวเองก็ไม่ได้  อยากถามว่า โค๊ดตัวไหน ที่ปรับแก้ การบล๊อก ไอพี อะครับ   ขอบคุณครับ

**Comment by pawarit123** [comment]
คือใส่รหัสผิด แล้วโดนบล๊อค อะครั บ

**Comment by robocon** [comment]
ในหน้า admin ถ้าต้องการยกเลิกระบบแบนสามารถเข้าไปแก้ไขได้ที่
modules/admin/login.php บรรทัดที่ 172 หน้าตาโค้ดจะเป็นแบบนี้ครับ

``` $db->connectdb(DB_NAME,DB_USERNAME,DB_PASSWORD);
$db->add_db(TB_IPBLOCK,array(
    "ip"=>"".$IPADDRESS."",
    "post_date"=>"".time().""
));
$db->closedb ();
```

สามารถลบทิ้งออกไปได้เลยครับ

**Comment by windocter** [comment]
ในส่วนของ admin ที่จัดการเมนู บล้อกต่างๆที่มีอยุ่เช่น ที่ตั้งโรงเรียน ประวัติโรงเรียน เวลาเราแก้ไขข้อมุลภายในแล้ว ทำไมมันยังไม่แก้ไขให้ครับ กลับไปเป็นข้อมูลเดิม
