### ISSUE TITLE
กล่องข้อความ error

### ISSUE THREAD

**Issue by itsong** [robocon/easy1-template#2]
ทดสอบด้วย  xampp 1.7 หลังติดตั้ง กล่องข้อความ error

Deprecated: Assigning the return value of new by reference is deprecated in D:\xampp\htdocs\atomymaxsite\modules\smiletag\view.php on line 14

Deprecated: Assigning the return value of new by reference is deprecated in D:\xampp\htdocs\atomymaxsite\modules\smiletag\lib\St_XmlParser.class.php on line 36

Deprecated: Assigning the return value of new by reference is deprecated in D:\xampp\htdocs\atomymaxsite\modules\smiletag\lib\St_XmlParser.class.php on line 72

Deprecated: Assigning the return value of new by reference is deprecated in D:\xampp\htdocs\atomymaxsite\modules\smiletag\lib\St_XmlParser.class.php on line 119

Deprecated: Assigning the return value of new by reference is deprecated in D:\xampp\htdocs\atomymaxsite\modules\smiletag\lib\St_XmlParser.class.php on line 180

Deprecated: Assigning the return value of new by reference is deprecated in D:\xampp\htdocs\atomymaxsite\modules\smiletag\lib\St_XmlParser.class.php on line 238

Deprecated: Assigning the return value of new by reference is deprecated in D:\xampp\htdocs\atomymaxsite\modules\smiletag\lib\St_XmlParser.class.php on line 304

Deprecated: Assigning the return value of new by reference is deprecated in D:\xampp\htdocs\atomymaxsite\modules\smiletag\lib\St_XmlParser.class.php on line 368

Deprecated: Assigning the return value of new by reference is deprecated in D:\xampp\htdocs\atomymaxsite\modules\smiletag\lib\St_XmlParser.class.php on line 450

Deprecated: Assigning the return value of new by reference is deprecated in D:\xampp\htdocs\atomymaxsite\modules\smiletag\lib\St_XmlParser.class.php on line 498

Deprecated: Assigning the return value of new by reference is deprecated in D:\xampp\htdocs\atomymaxsite\modules\smiletag\lib\St_XmlParser.class.php on line 542

Deprecated: Assigning the return value of new by reference is deprecated in D:\xampp\htdocs\atomymaxsite\modules\smiletag\lib\St_XmlParser.class.php on line 559

Deprecated: Assigning the return value of new by reference is deprecated in D:\xampp\htdocs\atomymaxsite\modules\smiletag\lib\St_XmlParser.class.php on line 609

Deprecated: Assigning the return value of new by reference is deprecated in D:\xampp\htdocs\atomymaxsite\modules\smiletag\lib\St_XmlParser.class.php on line 626

Deprecated: Assigning the return value of new by reference is deprecated in D:\xampp\htdocs\atomymaxsite\modules\smiletag\lib\St_XmlParser.class.php on line 676

Deprecated: Assigning the return value of new by reference is deprecated in D:\xampp\htdocs\atomymaxsite\modules\smiletag\lib\St_XmlParser.class.php on line 707

Deprecated: Assigning the return value of new by reference is deprecated in D:\xampp\htdocs\atomymaxsite\modules\smiletag\lib\St_XmlParser.class.php on line 772

Deprecated: Assigning the return value of new by reference is deprecated in D:\xampp\htdocs\atomymaxsite\modules\smiletag\lib\St_XmlParser.class.php on line 821

Deprecated: Assigning the return value of new by reference is deprecated in D:\xampp\htdocs\atomymaxsite\modules\smiletag\lib\St_XmlParser.class.php on line 887

Deprecated: Assigning the return value of new by reference is deprecated in D:\xampp\htdocs\atomymaxsite\modules\smiletag\lib\St_XmlParser.class.php on line 937

Deprecated: Assigning the return value of new by reference is deprecated in D:\xampp\htdocs\atomymaxsite\modules\smiletag\lib\St_XmlParser.class.php on line 947

Deprecated: Assigning the return value of new by reference is deprecated in D:\xampp\htdocs\atomymaxsite\modules\smiletag\lib\St_ConfigManager.class.php on line 54

Deprecated: Assigning the return value of new by reference is deprecated in D:\xampp\htdocs\atomymaxsite\modules\smiletag\lib\St_FileDao.class.php on line 93

Deprecated: Assigning the return value of new by reference is deprecated in D:\xampp\htdocs\atomymaxsite\modules\smiletag\lib\St_FileDao.class.php on line 108

Deprecated: Assigning the return value of new by reference is deprecated in D:\xampp\htdocs\atomymaxsite\modules\smiletag\lib\St_FileDao.class.php on line 123

Deprecated: Assigning the return value of new by reference is deprecated in D:\xampp\htdocs\atomymaxsite\modules\smiletag\lib\St_FileDao.class.php on line 138

Deprecated: Assigning the return value of new by reference is deprecated in D:\xampp\htdocs\atomymaxsite\modules\smiletag\lib\St_FileDao.class.php on line 154

Deprecated: Assigning the return value of new by reference is deprecated in D:\xampp\htdocs\atomymaxsite\modules\smiletag\lib\St_FileDao.class.php on line 170

Deprecated: Assigning the return value of new by reference is deprecated in D:\xampp\htdocs\atomymaxsite\modules\smiletag\lib\St_FileDao.class.php on line 185

Deprecated: Assigning the return value of new by reference is deprecated in D:\xampp\htdocs\atomymaxsite\modules\smiletag\lib\St_FileDao.class.php on line 200

Deprecated: Assigning the return value of new by reference is deprecated in D:\xampp\htdocs\atomymaxsite\modules\smiletag\lib\St_FileDao.class.php on line 215

Deprecated: Assigning the return value of new by reference is deprecated in D:\xampp\htdocs\atomymaxsite\modules\smiletag\lib\St_FileDao.class.php on line 248

Deprecated: Assigning the return value of new by reference is deprecated in D:\xampp\htdocs\atomymaxsite\modules\smiletag\lib\St_FileDao.class.php on line 262

Deprecated: Assigning the return value of new by reference is deprecated in D:\xampp\htdocs\atomymaxsite\modules\smiletag\lib\St_FileDao.class.php on line 276

Deprecated: Assigning the return value of new by reference is deprecated in D:\xampp\htdocs\atomymaxsite\modules\smiletag\lib\St_FileDao.class.php on line 294

Deprecated: Assigning the return value of new by reference is deprecated in D:\xampp\htdocs\atomymaxsite\modules\smiletag\lib\St_FileDao.class.php on line 322

Deprecated: Assigning the return value of new by reference is deprecated in D:\xampp\htdocs\atomymaxsite\modules\smiletag\lib\St_PersistenceManager.class.php on line 104

Deprecated: Assigning the return value of new by reference is deprecated in D:\xampp\htdocs\atomymaxsite\modules\smiletag\lib\St_PersistenceManager.class.php on line 106

Deprecated: Assigning the return value of new by reference is deprecated in D:\xampp\htdocs\atomymaxsite\modules\smiletag\lib\St_ViewManager.class.php on line 21

Deprecated: Assigning the return value of new by reference is deprecated in D:\xampp\htdocs\atomymaxsite\modules\smiletag\lib\St_ViewManager.class.php on line 35

Deprecated: Assigning the return value of new by reference is deprecated in D:\xampp\htdocs\atomymaxsite\modules\smiletag\lib\St_ViewManager.class.php on line 55

Strict Standards: Non-static method DOMIT_Utilities::validateXML() should not be called statically, assuming $this from incompatible context in D:\xampp\htdocs\atomymaxsite\modules\smiletag\lib\domit\xml_domit_lite_parser.php on line 990

Strict Standards: Non-static method DOMIT_Utilities::validateXML() should not be called statically, assuming $this from incompatible context in D:\xampp\htdocs\atomymaxsite\modules\smiletag\lib\domit\xml_domit_lite_parser.php on line 990

Strict Standards: Non-static method DOMIT_Utilities::validateXML() should not be called statically, assuming $this from incompatible context in D:\xampp\htdocs\atomymaxsite\modules\smiletag\lib\domit\xml_domit_lite_parser.php on line 990

Strict Standards: Non-static method DOMIT_Utilities::validateXML() should not be called statically, assuming $this from incompatible context in D:\xampp\htdocs\atomymaxsite\modules\smiletag\lib\domit\xml_domit_lite_parser.php on line 990
admin [10:18:45]
avatar

:p
ad [10:03:56]
avatar

ทดสอบ
admin [23:02:26]
avatar

ทดสอบ
ad [22:58:52]
avatar

ฟก
Powered by smiletag

**Comment by robocon** [comment]
เป็นปัญหาที่ lib XML ของตัว smiletag ครับ
สร้างไฟล์ .htaccess ขึ้นมาแล้วใส่โค้ดตัวนี้เข้าไปครับ
มันจะปิด error ทั้งหมดในหน้าเว็บนั้น

``` php
<IfModule mod_php5.c>
php_value error_reporting 0
php_flag display_errors off
</IfModule>
```
